version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: hhvm/hhvm-proxygen:latest
        ports:
            - 8080:80
        volumes:
            - .:/var/www
            - logs:/var/www/logs
